# Generated by Django 5.0.3 on 2024-04-16 09:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100)),
                ('conn_name', models.CharField(max_length=100)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Postgres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('host', models.CharField(max_length=100)),
                ('port', models.IntegerField()),
                ('database_name', models.CharField(max_length=100)),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.service')),
            ],
        ),
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pipeline_name', models.CharField(max_length=100)),
                ('ingestion_status', models.BooleanField(default=False)),
                ('profiler_status', models.BooleanField(default=False)),
                ('cron_exp', models.CharField(max_length=100)),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.service')),
            ],
        ),
        migrations.CreateModel(
            name='Mysql',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('host', models.CharField(max_length=100)),
                ('port', models.IntegerField()),
                ('database_name', models.CharField(max_length=100)),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.service')),
            ],
        ),
        migrations.CreateModel(
            name='Mssql',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('host', models.CharField(max_length=100)),
                ('port', models.IntegerField()),
                ('database_name', models.CharField(max_length=100)),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.service')),
            ],
        ),
        migrations.CreateModel(
            name='TableMetaData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_count', models.IntegerField()),
                ('col_count', models.IntegerField()),
                ('table_name', models.CharField(max_length=100)),
                ('duplicates', models.IntegerField()),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.service')),
            ],
        ),
        migrations.CreateModel(
            name='Metrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('col_name', models.CharField(max_length=100)),
                ('col_type', models.CharField(max_length=100)),
                ('is_numeric', models.BooleanField(default=False)),
                ('null_values', models.IntegerField()),
                ('unique', models.IntegerField()),
                ('maximum', models.IntegerField(null=True)),
                ('minimum', models.IntegerField(null=True)),
                ('mean', models.IntegerField(null=True)),
                ('standard_deviation', models.IntegerField(null=True)),
                ('histogram_data', models.TextField()),
                ('bar_plot_data', models.TextField()),
                ('table', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.tablemetadata')),
            ],
        ),
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correlation', models.JSONField()),
                ('outliers', models.JSONField()),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.service')),
                ('table', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.tablemetadata')),
            ],
        ),
    ]
