# Generated by Django 5.0.3 on 2024-04-17 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablemetadata',
            name='col_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tablemetadata',
            name='duplicates',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tablemetadata',
            name='row_count',
            field=models.IntegerField(default=0),
        ),
    ]
