# Generated by Django 5.0.3 on 2024-04-17 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_tablemetadata_col_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.CharField()),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.service')),
                ('table_one', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='table_one', to='app.tablemetadata')),
                ('table_two', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='table_two', to='app.tablemetadata')),
            ],
        ),
    ]
