# Generated by Django 5.0.3 on 2024-04-18 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_tablerelation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablerelation',
            name='table_one',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='table_one_relations', to='app.tablemetadata'),
        ),
        migrations.AlterField(
            model_name='tablerelation',
            name='table_two',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='table_two_relations', to='app.tablemetadata'),
        ),
    ]
