# Generated by Django 5.0.3 on 2024-04-18 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_tablerelation_table_one_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metrics',
            name='bar_plot_data',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='metrics',
            name='histogram_data',
            field=models.TextField(null=True),
        ),
    ]
