# Generated by Django 5.0.3 on 2024-04-19 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_metrics_bar_plot_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='pipeline_name',
            field=models.CharField(default='a', max_length=100),
            preserve_default=False,
        ),
    ]
